### PR TITLE
fix(nrql_alert_condition): validate operator based on condition type

### LINKED ISSUE #1157: Baseline NRQL alert condition throws error
### Terraform Version

```
 terraform -v
Terraform v0.12.29
+ provider.newrelic v2.15.1

Your version of Terraform is out of date! The latest version
is 0.14.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

- `newrelic_nrql_alert_condition`

### Terraform Configuration

```hcl
resource "newrelic_nrql_alert_condition" "eventhub-eastus-outgoing-message-trend-outlier" {
  type                         = "baseline"
  account_id                   = var.account_id
  name                         = "EventHub outgoing message trend deviated"
  policy_id                    = data.newrelic_alert_policy.search_notify_slack.id
  enabled                      = true
  runbook_url                  = ""
  violation_time_limit_seconds = 3600

  baseline_direction = "lower_only"

  warning {
    threshold             = 2
    threshold_duration    = 60 * 15 // 15 minutes
    threshold_occurrences = "all"
  }

  critical {
    threshold             = 2
    threshold_duration    = 60 * 25 // 25 minutes
    threshold_occurrences = "all"
  }

  nrql {
    evaluation_offset = 5
    query             = "FROM AzureEventHubNamespaceSample SELECT sum(`outgoingMessages.Maximum`) WHERE entityName LIKE 'topic' AND displayName like 'prod-eventhub'"
  }
}
```

### Actual Behavior
What actually happened?

```
newrelic_nrql_alert_condition.eventhub-eastus-outgoing-message-trend-outlier: Creating...

Error: Argument "condition" has invalid value $condition.
In field "terms": Expected type "[AlertsNrqlDynamicConditionTermsInput!]!", found [{operator: "EQUALS", priority: "CRITICAL", threshold: 2, thresholdDuration: 1500, thresholdOccurrences: "ALL"}, {operator: "EQUALS", priority: "WARNING", threshold: 2, thresholdDuration: 900, thresholdOccurrences: "ALL"}].
In element #1: Expected type "AlertsNrqlDynamicConditionTermsInput", found {operator: "EQUALS", priority: "CRITICAL", threshold: 2, thresholdDuration: 1500, thresholdOccurrences: "ALL"}.
In field "operator": Expected type "AlertsNrqlDynamicConditionTermsOperator!", found "EQUALS".
In element #2: Expected type "AlertsNrqlDynamicConditionTermsInput", found {operator: "EQUALS", priority: "WARNING", threshold: 2, thresholdDuration: 900, thresholdOccurrences: "ALL"}.
In field "operator": Expected type "AlertsNrqlDynamicConditionTermsOperator!", found "EQUALS".

  on eventhub.tf line 2, in resource "newrelic_nrql_alert_condition" "eventhub-eastus-outgoing-message-trend-outlier":
   2: resource "newrelic_nrql_alert_condition" "eventhub-eastus-outgoing-message-trend-outlier" {
```

### Expected Behavior
What should have happened?

`terraform apply` should have successfully created NRQL alert condition.

### Steps to Reproduce
Attempt to create the resource by running `terraform apply` would reproduce the issue.

### PR DESCRIPTION
**Pull request by zlesnr**
fixes #1157

Without this change, we attempt to set an invalid operator on baseline and
outlier conditions.  This looks to be a change in the upstream API to perform
more validation, which is then surfaced as an API error to the Terraform user,
but without the needed context about why the call was invalid.  Here we catch
this condition during the expandNrqlConditionTerm code to ensure that we don't
attempt to make the call, and give back a reasonable error to the user.

### CODE REVIEW

File: newrelic/structures_newrelic_nrql_alert_condition.go [hunk 1]
```diff
@@ -171,6 +171,13 @@ func expandNrqlConditionTerm(term map[string]interface{}, conditionType, priorit
 		return nil, fmt.Errorf("one of `duration` or `threshold_duration` must be configured for block `term`, but not both")
 	}
 
+	switch conditionType {
+	case "baseline", "outlier":
+		if strings.ToUpper(term["operator"].(string)) != "ABOVE" {
```
Comment (sanderblue) [inline newrelic/structures_newrelic_nrql_alert_condition.go:176]: I think we have these as an enum value in the client

Comment (zlesnr) [reply newrelic/structures_newrelic_nrql_alert_condition.go]: Updated.

**Review by sanderblue — APPROVED** [review]
