### PR TITLE
fix(dashboards): code changes to enable dashboards with empty pages

### LINKED ISSUE #2376: Error creating dashboard from json
### NewRelic Version
3.23.0

### Terraform Version
1.2.8

### Affected Resource(s)
newrelic_one_dashboard_json

### Terraform Configuration
```
provider "newrelic" {
  account_id = "123456"
  api_key    = "XXX"
  region     = "EU"
}

resource "newrelic_one_dashboard_json" "environment" {
    json = file("${path.module}/dashboards/environment.json")
}
```
Dashboard json below:

```
{
    "name": "XXX",
    "description": null,
    "permissions": "PUBLIC_READ_WRITE",
    "pages": [
      {
        "name": "XXX",
        "description": null,
        "widgets": [
          {
            "title": "Load Balancer Latency",
            "layout": {
              "column": 1,
              "row": 1,
              "width": 4,
              "height": 3
            },
            "linkedEntityGuids": null,
            "visualization": {
              "id": "viz.line"
            },
            "rawConfiguration": {
              "facet": {
                "showOtherSeries": false
              },
              "legend": {
                "enabled": true
              },
              "nrqlQueries": [
                {
                  "accountIds": [
                    3875837
                  ],
                  "query": "SELECT average(`aws.elb.Latency`), average(`aws.elb.Latency.p99`), average(`aws.elb.Latency.p95`) FROM Metric WHERE `aws.elb.LoadBalancerName` = 'XXX' AND `collector.name` = 'cloudwatch-metric-streams' AND `aws.accountId` = 'XXX' TIMESERIES"
                }
              ],
              "platformOptions": {
                "ignoreTimeRange": false
              },
              "units": {
                "unit": "SECONDS"
              },
              "yAxisLeft": {
                "zero": true
              }
            }
          }
        ]
      },
      {
        "name": "vault",
        "description": null,
        "widgets": []
      },
      {
        "name": "xenolith",
        "description": null,
        "widgets": []
      }
    ],
    "variables": []
  }
```
### Actual Behavior
```
 Error: Argument "dashboard" has invalid value $dashboard.
│ In field "pages": Expected type "[DashboardPageInput!]!", found [{name: "krakatoa", widgets: [{configuration: {}, layout: {column: 1, height: 3, row: 1, width: 4}, linkedEntityGuids: null, rawConfiguration: {facet: {showOtherSeries: false}, legend: {enabled: true}, nrqlQueries: [{accountIds: [3875837], query: "SELECT average(`aws.elb.Latency`), average(`aws.elb.Latency.p99`), average(`aws.elb.Latency.p95`) FROM Metric WHERE `aws.elb.LoadBalancerName` = 'staging-krakatoa-elb' AND `collector.name` = 'cloudwatch-metric-streams' AND `aws.accountId` = '281255908620' TIMESERIES"}], platformOptions: {ignoreTimeRange: false}, units: {unit: "SECONDS"}, yAxisLeft: {zero: true}}, title: "Load Balancer Latency", visualization: {id: "viz.line"}}]}, {name: "vault"}, {name: "xenolith"}].
│ In field "facet": Unknown field.
│ In field "legend": Unknown field.
│ In field "nrqlQueries": Unknown field.
│ In field "platformOptions": Unknown field.
│ In field "units": Unknown field.
│ In field "yAxisLeft": Unknown field.
│ In element #2: Expected type "DashboardPageInput", found {name: "vault"}.
│ In field "widgets": Expected type "[DashboardWidgetInput!]!", found null.
│ In element #3: Expected type "DashboardPageInput", found {name: "xenolith"}.
│ In field "widgets": Expected type "[DashboardWidgetInput!]!", found null.
│ 
│   with module.aws_link.newrelic_one_dashboard_json.environment,
│   on modules/aws_link/dashboards.tf line 1, in resource "newrelic_one_dashboard_json" "environment":
│    1: resource "newrelic_one_dashboard_json" "environment" {
```

### Expected Behavior
Dashboard should be created successfully. I created it manually in NewRelic then copied the json, so should be valid.

### Steps to Reproduce
terraform apply

### PR DESCRIPTION
**Pull request by pranav-new-relic**
# Description

This PR addresses a fix to #2376 to enable creating dashboards with empty pages (i.e. with pages comprising no widgets) and tests to validate the same.

#### A Gist of The Change
- The reason why a dashboard cannot be created with a page with no widgets is because an empty list needs to be sent to the API when there are no widgets; and the following explain the problems
    - The attribute **[]DashboardWidgetInput** is configured to omit empty values in client-go; so sending an empty list would make it null, which is not expected by the API. If there are no widgets, the API expects to receive an empty list **[]**, to enable which **omitempty** in client-go has been removed in this PR: https://github.com/newrelic/newrelic-client-go/pull/1033/
    - Even with the above fix, in the one_dashboard_raw and one_dashboard resources, the list is not initialised if no widgets are added to the configuration, so minor code changes are needed to do so.
   

#### Newly Added Tests
Tests have been added to validate the creation of a dashboard with empty pages. 
**These tests would fail until the following changes in newrelic-client-go are merged, released and consumed by this PR.**

https://github.com/newrelic/newrelic-client-go/pull/1033/files#diff-68cf5c0b92d6cadf0d433b0b51274d5e50a1013a1a2f73840b89df69d20980daL262

However, these have been found to be working fine locally. The following image shows the behaviour of these tests before and after the change in client-go.

image

Fixes #2376 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

Please delete options that are not relevant.

- [x] My commit message follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] My code is formatted to [Go standards](https://go.dev/blog/gofmt)
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes. Go [here](https://github.com/newrelic/terraform-provider-newrelic#testing) for instructions on running tests locally.

### CODE REVIEW

File: newrelic/structures_newrelic_one_dashboard.go [hunk 1]
```diff
@@ -169,6 +169,7 @@ func expandDashboardPageInput(d *schema.ResourceData, pages []interface{}, meta
 			page.GUID = common.EntityGUID(guid.(string))
 		}
 
+		page.Widgets = []dashboards.DashboardWidgetInput{}
```
Comment (pranav-new-relic) [inline newrelic/structures_newrelic_one_dashboard.go:172]: Note for the reviewer
- The list has been initialised here in order to be able to send an empty list to the API even when no widgets are added to the Terraform Configuration
- Without this change, an empty list would not be sent to client-go when no widgets are added, and instead, **null** would be sent, causing the existing problem again

**Review by RavitejaSurampudi — APPROVED** [review]
